# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Killport < Formula
  desc "Free a TCP Port by terminating its Occupant"
  homepage "https://github.com/jawharmed/kill-port"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jawharmed/kill-port/releases/download/v1.0.0/killport_Darwin_x86_64.tar.gz"
      sha256 "34ff33201b867d75846740685ac9e1046d4f41e725cdd02808a1413de76c6758"

      define_method(:install) do
        bin.install "killport"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jawharmed/kill-port/releases/download/v1.0.0/killport_Darwin_arm64.tar.gz"
      sha256 "a4e0394df700096ee8bc12dd124c51bf1bf1c551ffe39d73d2b3076632c6d3d5"

      define_method(:install) do
        bin.install "killport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jawharmed/kill-port/releases/download/v1.0.0/killport_Linux_x86_64.tar.gz"
      sha256 "cdc49b47c81c62ba3b7a2e085aadac07b2a1b5c6d6009c75e813462ef647a332"
      define_method(:install) do
        bin.install "killport"
      end
    end
  end

  test do
    assert_match "killport version", shell_output("#{bin}/killport --version")
  end
end
